version: '3.9'
services:
  db:
    image: postgres:12
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5433:5434
    volumes:
      - pgdata:/var/lib/postgresql/data
  nodeapp:
    container_name: node-api-typeorm
    build:
      context: .
      dockerfile: dockerfile
    image: api-typeorm
    env_file: ./.env
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - PORT=${DB_PORT}
      - DB_HOST=db
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
volumes:
  pgdata: {}
